import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { WalletBar } from "@/components/WalletBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen">
            <div className="border-b border-[var(--panel-border)] bg-[var(--panel)] backdrop-blur">
              <div className="max-w-3xl mx-auto px-6 py-4">
                <WalletBar />
              </div>
            </div>
            <div className="pb-12">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
